// Mock data for demo mode. Enable by setting DEMO_MODE=true in environment variables.

export const DEMO_USER = {
  id: "demo-admin-001",
  name: "Administrador Demo",
  email: "admin@dyrlo.com",
  role: "ADMIN",
  locationId: "demo-location-001",
};

const today = new Date().toISOString();
const yesterday = new Date(Date.now() - 86400000).toISOString();

export const DEMO_REPORTES = {
  kpis: {
    ordersToday: 8,
    ordersTotal: 142,
    litersToday: 24.5,
    revenueToday: 4800,
    queueCount: 3,
    avgProductionTime: 22,
    unpaidOrders: 5,
  },
  charts: {
    salesByGroup: [
      { group: "Básicos", revenue: 18500, liters: 82, count: 45 },
      { group: "Premium", revenue: 32000, liters: 64, count: 38 },
      { group: "Metálicos", revenue: 14000, liters: 28, count: 22 },
      { group: "Especiales", revenue: 8500, liters: 17, count: 12 },
    ],
    ordersBySource: [
      { source: "MOSTRADOR", count: 68 },
      { source: "VENTAS", count: 34 },
      { source: "WHATSAPP", count: 25 },
      { source: "REDES_SOCIALES", count: 15 },
    ],
    productionDaily: [
      { date: "2026-05-12", count: 18, avg_time: 19 },
      { date: "2026-05-13", count: 22, avg_time: 21 },
      { date: "2026-05-14", count: 15, avg_time: 24 },
      { date: "2026-05-15", count: 20, avg_time: 18 },
      { date: "2026-05-16", count: 25, avg_time: 22 },
      { date: "2026-05-17", count: 19, avg_time: 20 },
      { date: "2026-05-18", count: 8, avg_time: 22 },
    ],
    igualadorPerformance: [
      { name: "Carlos López", count: 89, avgTime: 21 },
      { name: "Ana Martínez", count: 53, avgTime: 24 },
    ],
  },
};

export const DEMO_PEDIDOS = [
  {
    id: "demo-order-001",
    folio: "P-2026-142",
    status: "PENDIENTE",
    colorName: "Blanco Hueso",
    liters: 4,
    pricePerLiter: 180,
    totalPrice: 720,
    source: "MOSTRADOR",
    queuePosition: 1,
    notes: null,
    createdAt: today,
    updatedAt: today,
    completedAt: null,
    productionTimeMinutes: null,
    client: { name: "Roberto Sánchez", email: "roberto@email.com", phone: "555-1234" },
    seller: { name: "María García" },
    igualador: null,
    colorGroup: { name: "Básicos" },
    payments: [],
  },
  {
    id: "demo-order-002",
    folio: "P-2026-141",
    status: "EN_PROCESO",
    colorName: "Gris Perla",
    liters: 2,
    pricePerLiter: 220,
    totalPrice: 440,
    source: "WHATSAPP",
    queuePosition: 2,
    notes: "Urgente",
    createdAt: today,
    updatedAt: today,
    completedAt: null,
    productionTimeMinutes: null,
    client: { name: "Laura Jiménez", email: "laura@empresa.com", phone: "555-5678" },
    seller: { name: "María García" },
    igualador: { name: "Carlos López" },
    colorGroup: { name: "Premium" },
    payments: [],
  },
  {
    id: "demo-order-003",
    folio: "P-2026-140",
    status: "LISTO",
    colorName: "Azul Marino",
    liters: 1,
    pricePerLiter: 250,
    totalPrice: 250,
    source: "VENTAS",
    queuePosition: null,
    notes: null,
    createdAt: yesterday,
    updatedAt: today,
    completedAt: today,
    productionTimeMinutes: 18,
    client: { name: "Fernando Torres", email: null, phone: "555-9012" },
    seller: { name: "María García" },
    igualador: { name: "Carlos López" },
    colorGroup: { name: "Premium" },
    payments: [{ id: "pay-001", amount: 250, method: "EFECTIVO", createdAt: today }],
  },
  {
    id: "demo-order-004",
    folio: "P-2026-139",
    status: "FACTURADO",
    colorName: "Rojo Ferrari",
    liters: 0.5,
    pricePerLiter: 350,
    totalPrice: 175,
    source: "REDES_SOCIALES",
    queuePosition: null,
    notes: null,
    createdAt: yesterday,
    updatedAt: yesterday,
    completedAt: yesterday,
    productionTimeMinutes: 25,
    client: { name: "Sofía Ramírez", email: "sofia@gmail.com", phone: "555-3456" },
    seller: { name: "María García" },
    igualador: { name: "Ana Martínez" },
    colorGroup: { name: "Metálicos" },
    payments: [{ id: "pay-002", amount: 175, method: "TRANSFERENCIA", createdAt: yesterday }],
  },
];

export const DEMO_CLIENTES = [
  {
    id: "demo-client-001",
    name: "Roberto Sánchez",
    email: "roberto@email.com",
    phone: "555-1234",
    company: null,
    notes: "Cliente frecuente",
    allowCredit: false,
    active: true,
    createdAt: "2026-01-15T10:00:00.000Z",
  },
  {
    id: "demo-client-002",
    name: "Laura Jiménez",
    email: "laura@empresa.com",
    phone: "555-5678",
    company: "Constructora Jiménez",
    notes: null,
    allowCredit: true,
    active: true,
    createdAt: "2026-02-20T10:00:00.000Z",
  },
  {
    id: "demo-client-003",
    name: "Fernando Torres",
    email: null,
    phone: "555-9012",
    company: null,
    notes: null,
    allowCredit: false,
    active: true,
    createdAt: "2026-03-05T10:00:00.000Z",
  },
  {
    id: "demo-client-004",
    name: "Sofía Ramírez",
    email: "sofia@gmail.com",
    phone: "555-3456",
    company: "Decoraciones Ramírez",
    notes: "Prefiere pagos con tarjeta",
    allowCredit: true,
    active: true,
    createdAt: "2026-03-18T10:00:00.000Z",
  },
];

export const DEMO_PRODUCCION = {
  queue: [
    {
      id: "demo-order-001",
      folio: "P-2026-142",
      status: "PENDIENTE",
      colorName: "Blanco Hueso",
      liters: 4,
      queuePosition: 1,
      notes: null,
      createdAt: today,
      client: { name: "Roberto Sánchez" },
      seller: { name: "María García" },
      igualador: null,
      colorGroup: { name: "Básicos" },
    },
    {
      id: "demo-order-002",
      folio: "P-2026-141",
      status: "EN_PROCESO",
      colorName: "Gris Perla",
      liters: 2,
      queuePosition: 2,
      notes: "Urgente",
      createdAt: today,
      client: { name: "Laura Jiménez" },
      seller: { name: "María García" },
      igualador: { name: "Carlos López" },
      colorGroup: { name: "Premium" },
    },
    {
      id: "demo-order-005",
      folio: "P-2026-143",
      status: "PENDIENTE",
      colorName: "Verde Esmeralda",
      liters: 1.5,
      queuePosition: 3,
      notes: null,
      createdAt: today,
      client: { name: "Sofía Ramírez" },
      seller: { name: "María García" },
      igualador: null,
      colorGroup: { name: "Especiales" },
    },
  ],
  completedToday: [
    {
      id: "demo-order-003",
      folio: "P-2026-140",
      status: "LISTO",
      colorName: "Azul Marino",
      liters: 1,
      completedAt: today,
      client: { name: "Fernando Torres" },
      igualador: { name: "Carlos López" },
      colorGroup: { name: "Premium" },
    },
  ],
};

export const DEMO_USUARIOS = [
  {
    id: "demo-admin-001",
    name: "Administrador",
    email: "admin@dyrlo.com",
    role: "ADMIN",
    active: true,
    locationId: "demo-location-001",
    location: { name: "Sucursal Principal" },
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "demo-vendedor-001",
    name: "María García",
    email: "vendedor@dyrlo.com",
    role: "VENDEDOR",
    active: true,
    locationId: "demo-location-001",
    location: { name: "Sucursal Principal" },
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "demo-igualador-001",
    name: "Carlos López",
    email: "igualador@dyrlo.com",
    role: "IGUALADOR",
    active: true,
    locationId: "demo-location-001",
    location: { name: "Sucursal Principal" },
    createdAt: "2026-01-01T00:00:00.000Z",
  },
];

export const DEMO_PRECIOS = [
  {
    id: "demo-group-001",
    name: "Básicos",
    description: "Blancos, negros y grises",
    sortOrder: 1,
    active: true,
    priceTiers: [
      { id: "t1", minLiters: 0.5, maxLiters: 3.99, pricePerLiter: 180 },
      { id: "t2", minLiters: 4, maxLiters: 9.99, pricePerLiter: 160 },
      { id: "t3", minLiters: 10, maxLiters: 99.99, pricePerLiter: 140 },
    ],
  },
  {
    id: "demo-group-002",
    name: "Premium",
    description: "Colores especiales y pasteles",
    sortOrder: 2,
    active: true,
    priceTiers: [
      { id: "t4", minLiters: 0.5, maxLiters: 3.99, pricePerLiter: 220 },
      { id: "t5", minLiters: 4, maxLiters: 9.99, pricePerLiter: 200 },
      { id: "t6", minLiters: 10, maxLiters: 99.99, pricePerLiter: 180 },
    ],
  },
  {
    id: "demo-group-003",
    name: "Metálicos",
    description: "Colores metálicos y perlados",
    sortOrder: 3,
    active: true,
    priceTiers: [
      { id: "t7", minLiters: 0.5, maxLiters: 3.99, pricePerLiter: 280 },
      { id: "t8", minLiters: 4, maxLiters: 9.99, pricePerLiter: 250 },
      { id: "t9", minLiters: 10, maxLiters: 99.99, pricePerLiter: 220 },
    ],
  },
  {
    id: "demo-group-004",
    name: "Especiales",
    description: "Colores de edición limitada",
    sortOrder: 4,
    active: true,
    priceTiers: [
      { id: "t10", minLiters: 0.5, maxLiters: 3.99, pricePerLiter: 350 },
      { id: "t11", minLiters: 4, maxLiters: 9.99, pricePerLiter: 320 },
    ],
  },
];

export const DEMO_AUDIT = [
  {
    id: "audit-001",
    userId: "demo-admin-001",
    user: { name: "Administrador", email: "admin@dyrlo.com" },
    action: "CREATE",
    entity: "Order",
    entityId: "demo-order-001",
    changes: { folio: "P-2026-142", colorName: "Blanco Hueso", liters: 4 },
    metadata: { folio: "P-2026-142" },
    createdAt: today,
  },
  {
    id: "audit-002",
    userId: "demo-vendedor-001",
    user: { name: "María García", email: "vendedor@dyrlo.com" },
    action: "UPDATE",
    entity: "Order",
    entityId: "demo-order-002",
    changes: { status: "EN_PROCESO" },
    metadata: { folio: "P-2026-141" },
    createdAt: today,
  },
  {
    id: "audit-003",
    userId: "demo-igualador-001",
    user: { name: "Carlos López", email: "igualador@dyrlo.com" },
    action: "UPDATE",
    entity: "Order",
    entityId: "demo-order-003",
    changes: { status: "LISTO", productionTimeMinutes: 18 },
    metadata: { folio: "P-2026-140" },
    createdAt: today,
  },
];
